#!/usr/bin/env python3
"""Batch generate Post AI clips from Episode 1 script."""
import urllib.request, json, sys, os, time

DID_CONFIG = os.environ.get("D_ID_AUTH_FILE", os.path.expanduser("~/.d-id-auth"))
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLIP_DIR = os.path.join(REPO_ROOT, "clips")

# Clip definitions from Episode 1 (SOCIAL-STRATEGY.md)
CLIPS = [
    {
        "id": "clip-001",
        "text": "Eleven people. Two hundred million dollars. No sales team. No marketing. No venture capital. That is Midjourney. Marco thinks it is an unrepeatable outlier. Lena says it is the blueprint for every post-AI company. They debated for 47 minutes. Full episode on Post AI Sessions.",
        "voice": "en-US-DavisNeural",
        "hook": "11 people. $200M. No sales team."
    },
    {
        "id": "clip-002",
        "text": "The top ten AI-native startups average three point four eight million dollars per employee. The top ten traditional SaaS companies average six hundred ten thousand. That is a five point seven x gap. And it is not explained by technology. It is explained by architecture. More data like this every week in the Post AI Index.",
        "voice": "en-US-DavisNeural",
        "hook": "$3.48M per employee vs $610K."
    },
    {
        "id": "clip-003",
        "text": "Midjourney is a fluke. It was the right product, at the right moment, on the right platform. Discord had one hundred seventy five million users. That is not strategy. That is timing. Show me another company that can replicate this. Show me the data. I will wait.",
        "voice": "en-US-DavisNeural",
        "hook": "Midjourney is a fluke."
    },
    {
        "id": "clip-004",
        "text": "Block cut four thousand jobs. Forty percent of the company. The stock went up twenty four percent in a single day. Meta cut eight thousand. Intuit cut three thousand while raising guidance. None of these companies were in trouble. The market is pricing organizational efficiency now. Welcome to the post-AI era.",
        "voice": "en-US-DavisNeural",
        "hook": "Block cut 4,000 jobs. Stock surged 24%."
    },
    {
        "id": "clip-005",
        "text": "I tested an AI CFO agent last week. It lasted three days. Day one, it categorized our AWS bill as miscellaneous entertainment. Day two, it flagged the entire engineering payroll as potential vendor duplication. Day three, it proposed taking our tax reserve and investing it in AI ETFs. The problem was not the AI. The problem was confidence.",
        "voice": "en-US-DavisNeural",
        "hook": "I tested an AI CFO. It lasted 3 days."
    },
    {
        "id": "clip-006",
        "text": "Here is the question nobody can answer. If you redesigned your company tomorrow with one constraint, no role that exists purely because that is how companies work, how many people would you actually need. The answer is probably uncomfortable. But it is less uncomfortable than discovering the answer three years from now.",
        "voice": "en-US-DavisNeural",
        "hook": "How many people would you actually need?"
    },
    {
        "id": "clip-007",
        "text": "Cursor hit one hundred million dollars in annual recurring revenue with roughly twenty people. That is five million dollars per person. Forty percent of their internal pull requests are now generated by their own AI agents. The product builds the product. This is not dogfooding. This is recursion.",
        "voice": "en-US-DavisNeural",
        "hook": "20 people. $100M. The product builds itself."
    },
    {
        "id": "clip-008",
        "text": "AI native companies are not more efficient because they use AI tools. They are more efficient because they were designed from day zero around the assumption that intelligence is abundant and cheap. Traditional companies were designed around the opposite assumption. Adding AI to a traditional org chart is like adding electric motors to a steam powered factory. The architecture limits the gains.",
        "voice": "en-US-DavisNeural",
        "hook": "Electric motors in a steam factory."
    },
]

def get_token():
    with open(DID_CONFIG) as f:
        return f.read().strip()

def create_talk(text, voice):
    token = get_token()
    data = {
        "script": {"type": "text", "input": text, "provider": {"type": "microsoft", "voice_id": voice}},
        "config": {"fluent": True, "pad_audio": 0.5, "result_format": "mp4"}
    }
    req = urllib.request.Request(
        "https://api.d-id.com/talks",
        data=json.dumps(data).encode(),
        headers={"Authorization": f"Basic {token}", "Content-Type": "application/json", "Accept": "application/json"}
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read())

def check_talk(talk_id):
    token = get_token()
    req = urllib.request.Request(
        f"https://api.d-id.com/talks/{talk_id}",
        headers={"Authorization": f"Basic {token}", "Accept": "application/json"}
    )
    with urllib.request.urlopen(req, timeout=10) as resp:
        return json.loads(resp.read())

if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "list"
    
    if cmd == "list":
        for c in CLIPS:
            print(f"  {c['id']}: {c['hook']}")
        print(f"\nTotal: {len(CLIPS)} clips")
    
    elif cmd == "create":
        idx = int(sys.argv[2]) - 1
        if 0 <= idx < len(CLIPS):
            c = CLIPS[idx]
            print(f"Creating {c['id']}: {c['hook']}")
            r = create_talk(c["text"], c["voice"])
            print(f"  id: {r['id']} | status: {r['status']}")
            print(f"  Check: python did_pipeline.py check {r['id']} {c['id']}")
    
    elif cmd == "check":
        tid = sys.argv[2]
        cid = sys.argv[3] if len(sys.argv) > 3 else tid
        r = check_talk(tid)
        print(f"status: {r.get('status')} | duration: {r.get('duration', '?')}s")
        if r.get('status') == 'done':
            url = r['result_url']
            out = os.path.join(CLIP_DIR, f"{cid}.mp4")
            print(f"Downloading {url} → {out}...")
            urllib.request.urlretrieve(url, out)
            print(f"Done! {os.path.getsize(out)} bytes")
    
    elif cmd == "all":
        # Create all clips
        for i, c in enumerate(CLIPS):
            out = os.path.join(CLIP_DIR, f"{c['id']}.mp4")
            if os.path.exists(out):
                print(f"[{i+1}/{len(CLIPS)}] {c['id']}: already exists")
                continue
            print(f"[{i+1}/{len(CLIPS)}] Creating {c['id']}: {c['hook'][:60]}...")
            r = create_talk(c["text"], c["voice"])
            print(f"  id: {r['id']} | status: {r['status']}")
            time.sleep(1)
